import type { Metadata } from 'next'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import GlobalStyleProvider from '@/providers/GlobalStyleProvider'
import ContextProvider from '@/providers/ContextProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <GlobalStyleProvider>
            <Sidebar />
            {children}
          </GlobalStyleProvider>
        </ContextProvider>
      </body>
    </html>
  )
}
